export const FETCH_RECIPES_BEGIN = 'FETCH_RECIPES_BEGIN'
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE'

export const CREATE_RECIPE_BEGIN = 'CREATE_RECIPE_BEGIN'
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS'
export const CREATE_RECIPE_FAILURE = 'CREATE_RECIPE_FAILURE'

export const DELETE_RECIPE_BEGIN = 'DELETE_RECIPE_BEGIN'
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS'
export const DELETE_RECIPE_FAILURE = 'DELETE_RECIPE_FAILURE'

export const UPDATE_RECIPE_BEGIN = 'UPDATE_RECIPE_BEGIN'
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS'
export const UPDATE_RECIPE_FAILURE = 'UPDATE_RECIPE_FAILURE'

export const FETCH_TAGS_BEGIN = 'FETCH_TAGS_BEGIN'
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE'

export const CREATE_TAG_BEGIN = 'CREATE_TAG_BEGIN'
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS'
export const CREATE_TAG_FAILURE = 'CREATE_TAG_FAILURE'

export const DELETE_TAG_BEGIN = 'DELETE_TAG_BEGIN'
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS'
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE'

export const UPDATE_TAG_BEGIN = 'UPDATE_TAG_BEGIN'
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS'
export const UPDATE_TAG_FAILURE = 'UPDATE_TAG_FAILURE'

export const UPDATE_FILTER = 'UPDATE_FILTER';
